### ISSUE TITLE
Convert from relative amplitude

### ISSUE THREAD

**Issue by mackiedrew** [mackiedrew/vam-online#214]
## Description of Feature, Bug, Change
We need a simple conversion factor that obviously can't be accurate, but something that will help us get a basic idea.

## Possible Implementation
- Change quietness cutoff to decibels based system.
- Change waveform to reflect decibels max and min instead of max amplitude
- http://stackoverflow.com/questions/2445756/how-can-i-calculate-audio-db-level

## Tasks
- [x] Remove maxAmplitude references and uses from display
- [x] Create amplitude to decibel coverter
- [x] Use decibels in wav form render
